# Generated by Django 3.1.7 on 2021-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primeiro Nome')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
